# Document templates for collections added to the Mongo database
#
# Documents in the database can be queried by any member 
# variable declared in the document class, or by the unique
# ObjectId generated by mongo

import mongoengine

# Represent a user and contains relevant metadata
class Users(mongoengine.Document):
    first_name = mongoengine.StringField(max_length = 50)
    last_name = mongoengine.StringField(max_length = 50)
    email = mongoengine.EmailField(required = True, unique = True)
    password = mongoengine.StringField(requred = True, min_length = 8)



